//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASP_F_E {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Headers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Headers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WASP_F_E.Headers", typeof(Headers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прийняти.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додавання нового долідження.
        /// </summary>
        public static string AddStudyWindow {
            get {
                return ResourceManager.GetString("AddStudyWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середня ефективність.
        /// </summary>
        public static string AverageEfficiency {
            get {
                return ResourceManager.GetString("AverageEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Побудувати графік.
        /// </summary>
        public static string BuildChart {
            get {
                return ResourceManager.GetString("BuildChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обчислити.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип обчислення.
        /// </summary>
        public static string CalculationType {
            get {
                return ResourceManager.GetString("CalculationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скасувати.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базова потужність (МВт).
        /// </summary>
        public static string CapacityBase {
            get {
                return ResourceManager.GetString("CapacityBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фактор завантаження (%).
        /// </summary>
        public static string CapacityFactor {
            get {
                return ResourceManager.GetString("CapacityFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пікова потужність (МВт).
        /// </summary>
        public static string CapacityPeak {
            get {
                return ResourceManager.GetString("CapacityPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальна потужність (МВт).
        /// </summary>
        public static string CapacityTotal {
            get {
                return ResourceManager.GetString("CapacityTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Графік.
        /// </summary>
        public static string ChartWindow {
            get {
                return ResourceManager.GetString("ChartWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть дослідження.
        /// </summary>
        public static string ChoseStudy {
            get {
                return ResourceManager.GetString("ChoseStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибір дослідження.
        /// </summary>
        public static string ChoseStudyWindow {
            get {
                return ResourceManager.GetString("ChoseStudyWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистити.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порівняти.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим порівняння:.
        /// </summary>
        public static string CompareMode {
            get {
                return ResourceManager.GetString("CompareMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порівняння досліджень.
        /// </summary>
        public static string CompareStudiesWindow {
            get {
                return ResourceManager.GetString("CompareStudiesWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви дісно бажаєте видалити дослідження?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викиди.
        /// </summary>
        public static string Emission {
            get {
                return ResourceManager.GetString("Emission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викиди.
        /// </summary>
        public static string Emissions {
            get {
                return ResourceManager.GetString("Emissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викиди.
        /// </summary>
        public static string EmissionsWindow {
            get {
                return ResourceManager.GetString("EmissionsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс енергії (ГВт/год).
        /// </summary>
        public static string EnergyBalance {
            get {
                return ResourceManager.GetString("EnergyBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базова енергія (МВт/год).
        /// </summary>
        public static string EnergyBase {
            get {
                return ResourceManager.GetString("EnergyBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попит на енергію (ГВт/год).
        /// </summary>
        public static string EnergyDemand {
            get {
                return ResourceManager.GetString("EnergyDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пікова енергія (МВт/год).
        /// </summary>
        public static string EnergyPeak {
            get {
                return ResourceManager.GetString("EnergyPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnergyPumped (МВт).
        /// </summary>
        public static string EnergyPumped {
            get {
                return ResourceManager.GetString("EnergyPumped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дефіцитна енергія (МВт/год).
        /// </summary>
        public static string EnergyShortage {
            get {
                return ResourceManager.GetString("EnergyShortage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Залита енергія (МВт/год).
        /// </summary>
        public static string EnergySpilled {
            get {
                return ResourceManager.GetString("EnergySpilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальна енергія (МВт/год).
        /// </summary>
        public static string EnergyTotal {
            get {
                return ResourceManager.GetString("EnergyTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вихід.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фільтр.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixsys файл.
        /// </summary>
        public static string FixsysFile {
            get {
                return ResourceManager.GetString("FixsysFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Норма вимушеного простою.
        /// </summary>
        public static string ForCell {
            get {
                return ResourceManager.GetString("ForCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для параметру:.
        /// </summary>
        public static string ForParameter {
            get {
                return ResourceManager.GetString("ForParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to по типах.
        /// </summary>
        public static string ForTypes {
            get {
                return ResourceManager.GetString("ForTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to по роках.
        /// </summary>
        public static string ForYears {
            get {
                return ResourceManager.GetString("ForYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З файлу.
        /// </summary>
        public static string FromFiles {
            get {
                return ResourceManager.GetString("FromFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З іншого дослідження.
        /// </summary>
        public static string FromOtherStudy {
            get {
                return ResourceManager.GetString("FromOtherStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вартість власного палива (т.$).
        /// </summary>
        public static string FuelDomestic {
            get {
                return ResourceManager.GetString("FuelDomestic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вартість іноземного палива (т.$).
        /// </summary>
        public static string FuelForeign {
            get {
                return ResourceManager.GetString("FuelForeign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальна вартість палива (т. $).
        /// </summary>
        public static string FuelTotal {
            get {
                return ResourceManager.GetString("FuelTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теплотворна здатність палива.
        /// </summary>
        public static string HeatValue {
            get {
                return ResourceManager.GetString("HeatValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гідроумова.
        /// </summary>
        public static string Hydrocondition {
            get {
                return ResourceManager.GetString("Hydrocondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість гідроумов.
        /// </summary>
        public static string HydroconditionsCount {
            get {
                return ResourceManager.GetString("HydroconditionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гідроелектростанції:.
        /// </summary>
        public static string HydroPlants {
            get {
                return ResourceManager.GetString("HydroPlants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список досліджень.
        /// </summary>
        public static string ListOfStudies {
            get {
                return ResourceManager.GetString("ListOfStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Імовірнісь втрати навантаження (%).
        /// </summary>
        public static string LOLP {
            get {
                return ResourceManager.GetString("LOLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантаженість (%).
        /// </summary>
        public static string MainProbability {
            get {
                return ResourceManager.GetString("MainProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaintenanceSpace (МВт).
        /// </summary>
        public static string MaintenanceSpace {
            get {
                return ResourceManager.GetString("MaintenanceSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система формування сценаріїв.
        /// </summary>
        public static string MainWindow {
            get {
                return ResourceManager.GetString("MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mersim файл.
        /// </summary>
        public static string MersimFile {
            get {
                return ResourceManager.GetString("MersimFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мінімальне навантаження (МВт).
        /// </summary>
        public static string MinimumLoad {
            get {
                return ResourceManager.GetString("MinimumLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість блоків.
        /// </summary>
        public static string NumberOfUnits {
            get {
                return ResourceManager.GetString("NumberOfUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вартість експулатації та обслуговування (т. $).
        /// </summary>
        public static string OaM {
            get {
                return ResourceManager.GetString("OaM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пікове навантаження (МВт).
        /// </summary>
        public static string PeakLoad {
            get {
                return ResourceManager.GetString("PeakLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Mineng (ГВт/год).
        /// </summary>
        public static string PeakMineng {
            get {
                return ResourceManager.GetString("PeakMineng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Період.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість періодів.
        /// </summary>
        public static string PeriodsCount {
            get {
                return ResourceManager.GetString("PeriodsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва станції.
        /// </summary>
        public static string PlantName {
            get {
                return ResourceManager.GetString("PlantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електростанції.
        /// </summary>
        public static string Plants {
            get {
                return ResourceManager.GetString("Plants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типи електростанцій.
        /// </summary>
        public static string PlantsTypes {
            get {
                return ResourceManager.GetString("PlantsTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електростанції.
        /// </summary>
        public static string PlantsWindow {
            get {
                return ResourceManager.GetString("PlantsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будьласка,підтвердіть видалення.
        /// </summary>
        public static string PleaseComnfirmDeleting {
            get {
                return ResourceManager.GetString("PleaseComnfirmDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електростанції.
        /// </summary>
        public static string PowerPlants {
            get {
                return ResourceManager.GetString("PowerPlants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервна потужність (МВт).
        /// </summary>
        public static string ReserveCapacity {
            get {
                return ResourceManager.GetString("ReserveCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти в Excel.
        /// </summary>
        public static string SaveInExcel {
            get {
                return ResourceManager.GetString("SaveInExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коротка назва.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показати.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показати/Редагувати.
        /// </summary>
        public static string ShowOrRead {
            get {
                return ResourceManager.GetString("ShowOrRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дослідження.
        /// </summary>
        public static string Study {
            get {
                return ResourceManager.GetString("Study", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата дослідження.
        /// </summary>
        public static string StudyData {
            get {
                return ResourceManager.GetString("StudyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роки дослідження.
        /// </summary>
        public static string StudyYears {
            get {
                return ResourceManager.GetString("StudyYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Термоелектростанції:.
        /// </summary>
        public static string ThermalPlants {
            get {
                return ResourceManager.GetString("ThermalPlants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальна потужність (МВт).
        /// </summary>
        public static string TotalCapacity {
            get {
                return ResourceManager.GetString("TotalCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальна генерація (ГВт/год).
        /// </summary>
        public static string TotalGeneration {
            get {
                return ResourceManager.GetString("TotalGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальна інформація.
        /// </summary>
        public static string TotalInformation {
            get {
                return ResourceManager.GetString("TotalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типи.
        /// </summary>
        public static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типи електростанцій.
        /// </summary>
        public static string TypesWindow {
            get {
                return ResourceManager.GetString("TypesWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необслужена енергія (ГВт/год).
        /// </summary>
        public static string UnservedEnergy {
            get {
                return ResourceManager.GetString("UnservedEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вага (кг).
        /// </summary>
        public static string ValueKG {
            get {
                return ResourceManager.GetString("ValueKG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значення (%).
        /// </summary>
        public static string ValuePercent {
            get {
                return ResourceManager.GetString("ValuePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varsys файл.
        /// </summary>
        public static string VarsysFile {
            get {
                return ResourceManager.GetString("VarsysFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рік.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
