//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASP_F_E {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Headers2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Headers2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WASP_F_E.Headers2", typeof(Headers2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new study.
        /// </summary>
        public static string AddNewStudy {
            get {
                return ResourceManager.GetString("AddNewStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Capacity (MW).
        /// </summary>
        public static string CapacityBase {
            get {
                return ResourceManager.GetString("CapacityBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity Factor (%).
        /// </summary>
        public static string CapacityFactor {
            get {
                return ResourceManager.GetString("CapacityFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Capacity (MW).
        /// </summary>
        public static string CapacityPeak {
            get {
                return ResourceManager.GetString("CapacityPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Capacity (MW).
        /// </summary>
        public static string CapacityTotal {
            get {
                return ResourceManager.GetString("CapacityTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose study.
        /// </summary>
        public static string ChoseStudy {
            get {
                return ResourceManager.GetString("ChoseStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare mode.
        /// </summary>
        public static string CompareMode {
            get {
                return ResourceManager.GetString("CompareMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emission.
        /// </summary>
        public static string Emission {
            get {
                return ResourceManager.GetString("Emission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Energy (MWh).
        /// </summary>
        public static string EnergyBase {
            get {
                return ResourceManager.GetString("EnergyBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Energy (MWh).
        /// </summary>
        public static string EnergyPeak {
            get {
                return ResourceManager.GetString("EnergyPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortage Energy (MWh).
        /// </summary>
        public static string EnergyShortage {
            get {
                return ResourceManager.GetString("EnergyShortage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spilled Energy (MWh).
        /// </summary>
        public static string EnergySpilled {
            get {
                return ResourceManager.GetString("EnergySpilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Energy (MWh).
        /// </summary>
        public static string EnergyTotal {
            get {
                return ResourceManager.GetString("EnergyTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixsys file.
        /// </summary>
        public static string FixsysFile {
            get {
                return ResourceManager.GetString("FixsysFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForCell.
        /// </summary>
        public static string ForCell {
            get {
                return ResourceManager.GetString("ForCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For parameter.
        /// </summary>
        public static string ForParameter {
            get {
                return ResourceManager.GetString("ForParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Types.
        /// </summary>
        public static string ForTypes {
            get {
                return ResourceManager.GetString("ForTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Years.
        /// </summary>
        public static string ForYears {
            get {
                return ResourceManager.GetString("ForYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From files.
        /// </summary>
        public static string FromFiles {
            get {
                return ResourceManager.GetString("FromFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From other study.
        /// </summary>
        public static string FromOtherStudy {
            get {
                return ResourceManager.GetString("FromOtherStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic fuel (K$).
        /// </summary>
        public static string FuelDomestic {
            get {
                return ResourceManager.GetString("FuelDomestic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign fuel ($K).
        /// </summary>
        public static string FuelForeign {
            get {
                return ResourceManager.GetString("FuelForeign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total fuel ($K).
        /// </summary>
        public static string FuelTotal {
            get {
                return ResourceManager.GetString("FuelTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydroconditions count.
        /// </summary>
        public static string HydroconditionsCount {
            get {
                return ResourceManager.GetString("HydroconditionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of studies.
        /// </summary>
        public static string ListOfStudies {
            get {
                return ResourceManager.GetString("ListOfStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lord Pos Pl.
        /// </summary>
        public static string LordPosPl {
            get {
                return ResourceManager.GetString("LordPosPl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Probability (%).
        /// </summary>
        public static string MainProbability {
            get {
                return ResourceManager.GetString("MainProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mersim file.
        /// </summary>
        public static string MersimFile {
            get {
                return ResourceManager.GetString("MersimFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of units.
        /// </summary>
        public static string NumberOfUnits {
            get {
                return ResourceManager.GetString("NumberOfUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation and Maintenance (K$).
        /// </summary>
        public static string OaM {
            get {
                return ResourceManager.GetString("OaM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Mineng.
        /// </summary>
        public static string PeakMineng {
            get {
                return ResourceManager.GetString("PeakMineng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods count.
        /// </summary>
        public static string PeriodsCount {
            get {
                return ResourceManager.GetString("PeriodsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Name.
        /// </summary>
        public static string PlantName {
            get {
                return ResourceManager.GetString("PlantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power plants.
        /// </summary>
        public static string PowerPlants {
            get {
                return ResourceManager.GetString("PowerPlants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Read.
        /// </summary>
        public static string ShowOrRead {
            get {
                return ResourceManager.GetString("ShowOrRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study.
        /// </summary>
        public static string Study {
            get {
                return ResourceManager.GetString("Study", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data of study.
        /// </summary>
        public static string StudyData {
            get {
                return ResourceManager.GetString("StudyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study years.
        /// </summary>
        public static string StudyYears {
            get {
                return ResourceManager.GetString("StudyYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value (kg).
        /// </summary>
        public static string ValueKG {
            get {
                return ResourceManager.GetString("ValueKG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varsys file.
        /// </summary>
        public static string VarsysFile {
            get {
                return ResourceManager.GetString("VarsysFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
